name: workflow_dispatch sample 1

on:
  workflow_dispatch:

jobs:
  printLog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Test Local Action
      id: test-action
      uses: arhagiwara/container-action-try@latest # Commit with the `v1` tag
      with:
        who-to-greet: hagiwara

    - name: Print Output
      id: output
      run: echo "${{ steps.test-action.outputs.greeting }}"
