name: workflow_dispatch sample 1

on:
  workflow_dispatch:

jobs:
  printLog:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      pull-requests: write
      contents: write
      
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Test Local Action
      id: test-action
      uses: arhagiwara/typescript-action@792382e62a0e3c198d3fa92e88f4803027660cff
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

