name: workflow_dispatch sample 1

on:
  workflow_dispatch:

jobs:
  printLog:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      pull-requests: write
    
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Test Local Action
      id: test-action
      uses: arhagiwara/typescript-action@e8d43ad3ae7b1e1bdb5935431031b4f02ab64cb8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

